import { Router } from 'express';
import healthRouter from './health.route';
import authRouter from '../modules/auth/route/auth.route';
import userRouter from '../modules/user/route/user.route';
import profileRouter from '../modules/user/route/profile.route';
import categoryRouter from '../modules/category/route/category.route';
import breedRouter from '../modules/breed/route/breed.route';
import listingRouter from '../modules/listing/route/listing.route';
import attributeRouter from '../modules/attribute/route/attribute.route';
import sellerRouter from '../modules/seller/route/seller.route';
import enquiryRouter from '../modules/enquiry/route/enquiry.route';
import homepageRouter from '../modules/homepage/route/homepage.route';
import uploadRouter from '../modules/upload/route/upload.route';
import wishlistRouter from '../modules/wishlist/route/wishlist.route';
import couponRouter from '../modules/coupon/route/coupon.route';
import orderRouter from '../modules/order/route/order.route';
import paymentRouter from '../modules/payment/route/payment.route';
import reviewRouter from '../modules/review/route/review.route';
import notificationRouter from '../modules/notification/route/notification.route';
import settingsRouter from '../modules/settings/route/settings.route';
import cmsRouter from '../modules/cms/route/cms.route';
import bannerRouter from '../modules/banner/route/banner.route';
import activityLogRouter from '../modules/activity-log/route/activity-log.route';
import dashboardRouter from '../modules/dashboard/route/dashboard.route';

const router = Router();

router.use('/health', healthRouter);
router.use('/auth', authRouter);
router.use('/users', userRouter);
router.use('/profile', profileRouter);
router.use('/categories', categoryRouter);
router.use('/breeds', breedRouter);
router.use('/listings', listingRouter);
router.use('/attributes', attributeRouter);
router.use('/sellers', sellerRouter);
router.use('/enquiries', enquiryRouter);
router.use('/homepage', homepageRouter);
router.use('/uploads', uploadRouter);
router.use('/wishlist', wishlistRouter);
router.use('/coupons', couponRouter);
router.use('/orders', orderRouter);
router.use('/payments', paymentRouter);
router.use('/reviews', reviewRouter);
router.use('/notifications', notificationRouter);
router.use('/settings', settingsRouter);
router.use('/cms', cmsRouter);
router.use('/banners', bannerRouter);
router.use('/activity-logs', activityLogRouter);
router.use('/dashboard', dashboardRouter);

export default router;
